# Generated by Django 3.2.1 on 2021-05-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_history',
            old_name='card_ID',
            new_name='card',
        ),
    ]
