# Generated by Django 3.2.1 on 2021-05-11 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_card_id_purchase_history_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='checkout.purchase_history'),
            preserve_default=False,
        ),
    ]
