# Generated by Django 3.2.1 on 2021-05-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='zip',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
