# Generated by Django 3.2.1 on 2021-05-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_purchase_history_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_history',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='firstName',
            field=models.CharField(default='Jane', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='lastName',
            field=models.CharField(default='Do', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='streetName',
            field=models.CharField(default='street', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='streetNumber',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='zip',
            field=models.FloatField(default=111),
            preserve_default=False,
        ),
    ]
