# Generated by Django 3.2.1 on 2021-05-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_checkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_history',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
