# Generated by Django 3.2.1 on 2021-05-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_purchase_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
