# Generated by Django 3.2.1 on 2021-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_checkout_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='quantity2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
