# Generated by Django 3.2.1 on 2021-05-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_checkout_quantity2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=255)),
                ('number', models.FloatField()),
                ('exp', models.DateTimeField()),
                ('cvc', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='quantity2',
        ),
    ]
