# Generated by Django 3.2.1 on 2021-05-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_auto_20210514_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_history',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.cards'),
            preserve_default=False,
        ),
    ]
