# Generated by Django 3.2.1 on 2021-05-14 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0016_purchase_history_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_history',
            name='card',
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='card_cvc',
            field=models.FloatField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='card_exp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='card_holder',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase_history',
            name='card_number',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
