# Generated by Django 3.2.1 on 2021-05-14 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_auto_20210514_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_history',
            name='card_exp_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='purchase_history',
            name='card_number',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000000000), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
    ]
