# Generated by Django 3.2.1 on 2021-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_type',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
